### ISSUE TITLE
style.use/unuse breaks hot reload style with react hot loader

### ISSUE THREAD

**Issue by MoOx** [bloodyowl/react-boilerplate#6]
The way the styles are currently imported & enabled/disabled make us unable to enjoy hot reload styles updates (or I am missing something).
Any idea how we can handle this ?

**Comment by ooflorent** [comment]
`style-loader` seems to handle it:
https://github.com/webpack/style-loader/blob/master/index.js#L20

**Comment by MoOx** [comment]
he use style/useable loader, not the default one.
And I just don't get any updates, so "not working for me" :)

**Comment by bloodyowl** [comment]
can you fork & create a repro so that I can see what's going on? thanks

**Comment by MoOx** [comment]
Closing since it's supposed to be fixed by style-loader 0.9.0 
Ref https://github.com/webpack/style-loader/pull/46
